### ISSUE TITLE
Re-write as Trello or other blacklisted project

### ISSUE THREAD

**Issue by rglassett** [appacademy/sample-project-proposal#3]
Don't encourage students to copy/paste.

**Comment by davidrunger** [comment]
FWIW, we currently have a simpler solution implemented:

> ... you may not clone Tumblr, as this is already architected for you in the sample project proposal.

From: https://github.com/appacademy/final-project-curriculum/blob/master/final-projects/final-projects.md
Added with: https://github.com/appacademy/final-project-curriculum/commit/cd3403af02728065a666bb65c5382d1cc8cf268c

I think that removing 1 out of 20 possible suggested apps to clone is acceptable, and personally don't think it's worth the trouble of re-writing the sample project proposal just so that students can clone Tumblr instead of one of the other 19 available apps.

**Comment by rglassett** [comment]
Great! I'll close this for now, then.
